// This runner is auto-generated by Brittle

runTests()

async function runTests() {
  const test = (await import('brittle')).default

  test.pause()

  await import('./vector.js')
  await import('./bm25.js')

  test.resume()
}
